Update ynh_system_reload

diff --git a/ynh_system_reload/ynh_system_reload b/ynh_system_reload/ynh_system_reload
--- a/ynh_system_reload/ynh_system_reload
+++ b/ynh_system_reload/ynh_system_reload
@@ -1,14 +1,14 @@
 #!/bin/bash
 
-# Reload (or restart) a service and print a log in case of failure.
+# Reload (or other actions) a service and print a log in case of failure.
 #
-# usage: ynh_system_reload service_name
+# usage: ynh_system_reload service_name [action]
 # | arg: service_name - Name of the service to reload
+# | arg: action - Action to perform with systemctl. Default: reload
 ynh_system_reload () {
         local service_name=$1
+        local action=${2:-reload}
 
-        # Reload the service (or restart if reload isn't available)
-        # The service will be started if it isn't
-        # And print the log if the service fail to start or reload
-        systemctl reload-or-restart $service_name || ( journalctl --lines=20 -u $service_name >&2 && false)
+        # Reload, restart or start and print the log if the service fail to start or reload
+        systemctl $action $service_name || ( journalctl --lines=20 -u $service_name >&2 && false)
 }
